### ISSUE TITLE
SuperCollider Intermittently Crashes

### ISSUE THREAD

**Issue by JRegimbal** [Shared-Reality-Lab/IMAGE-server#382]
Sometimes the SuperCollider service will crash without explanation. It will restart, but this means that the request will not be handled and the handler will time out on generating that audio. The message seems to be received, but no error logs are posted. In staging/production, this means the service will suddenly restart.

```
Received a message at /render/photo...
[E][01691.538371] mod.rtkit    | [  module-rtkit.c:  175 pw_rtkit_bus_get_system()] Failed to connect to system bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[W][01691.538392] mod.rtkit    | [  module-rtkit.c:  697 pipewire__module_init()] could not get system bus: Connection refused
[E][01691.539258] mod.protocol-native | [module-protocol-:  566 init_socket_name()] server 0x5587eb056350: name pipewire-0 is not an absolute path and no runtime dir found. Set one of PIPEWIRE_RUNTIME_DIR, XDG_RUNTIME_DIR or USERPROFILE in the environment
[E][01691.539289] pw.conf      | [          conf.c:  412 load_module()] 0x5587eb03b2a0: could not load mandatory module "libpipewire-module-protocol-native": No such file or directory
[E][01691.539399] default      | [      pipewire.c:  123 main()] failed to create context: No such file or directory
compiling class library...
        Found 714 primitives.
        Compiling directory '/usr/local/share/SuperCollider/SCClassLibrary'
        Compiling directory '/usr/local/share/SuperCollider/Extensions'
        Compiling directory '/home/sclang/.local/share/SuperCollider/Extensions'
        Compiling directory '/home/sclang/.local/share/SuperCollider/downloaded-quarks/MP3'
        Compiling directory '/home/sclang/.local/share/SuperCollider/downloaded-quarks/MathLib'
        Compiling directory '/home/sclang/.local/share/SuperCollider/downloaded-quarks/FileLog'
        Compiling directory '/home/sclang/.local/share/SuperCollider/downloaded-quarks/ExtraWindows'
        Compiling directory '/home/sclang/.local/share/SuperCollider/downloaded-quarks/SignalBox'
        Compiling directory '/home/sclang/.local/share/SuperCollider/downloaded-quarks/Hilbert'
        Compiling directory '/home/sclang/.local/share/SuperCollider/downloaded-quarks/XML'
        Compiling directory '/home/sclang/.local/share/SuperCollider/downloaded-quarks/wslib'
        Compiling directory '/home/sclang/.local/share/SuperCollider/downloaded-quarks/MatrixArray'
        Compiling directory '/home/sclang/.local/share/SuperCollider/downloaded-quarks/SphericalDesign'
        Compiling directory '/home/sclang/.local/share/SuperCollider/downloaded-quarks/atk-sc3'
        Compiling directory '/home/sclang/.local/share/SuperCollider/downloaded-quarks/SC-HOA'
        Compiling directory '/home/sclang/.local/share/SuperCollider/downloaded-quarks/Vowel'
        Compiling directory '/tmp/sc/IMAGE'
        numentries = 1422972 / 23058156 = 0.062
        6259 method selectors, 3684 classes
        method table size 24250928 bytes, big table size 184465248
        Number of Symbols 17075
        Byte Code Size 649671
        compiled 753 files in 0.29 seconds

Info: 9 methods are currently overwritten by extensions. To see which, execute:
MethodOverride.printAll

compile done
localhost : setting clientID to 0.
internal : setting clientID to 0.
Couldn't set realtime scheduling priority 1: Operation not permitted
MP3.lamepath automatically set to /usr/bin/lame
MP3.oggdecpath automatically set to /usr/bin/oggdec
Class tree inited in 0.02 seconds


*** Welcome to SuperCollider 3.12.2. *** For help type ctrl-c ctrl-h (Emacs) or :SChelp (vim) or ctrl-U (sced/gedit).
Couldn't set realtime scheduling priority 1: Operation not permitted
Generic Object Description
MINIMAL TEST IS LOADED
Semantic Segmentation Sonification
Single Line Chart
Autour-style Rendering
Photo Audio Rendering
```
Note that the errors/warnings reported occur on any start and seem to be a quirk of how our container is set up. It may be related to this issue, but doesn't directly trigger it.

**Comment by JRegimbal** [comment]
At least in this instance, the error was a segfault. This was found in the logs after:
```
sclang[3720837]: segfault at 5e ip 000000000042732b sp 00007f98f9abf2f0 error 4 in sclang[40d000+1f5000]
```
with the timestamp matching the container restart. Given that it occurred before a "Trying to render..." message was posted, it seems to have occurred between lines 203 and 206 in photo.scd.
https://github.com/Shared-Reality-Lab/IMAGE-server/blob/93600679d214cdbfd7f079615f05657b8c847d88/services/supercollider-images/supercollider-service/photo.scd#L203-L206

I've seen a reference that using try within control structures can cause problems, but can't find the actual issue itself. Will look for that.

**Comment by JRegimbal** [comment]
Was able to make it work in gdb.
```
grey count error
malloc(): unsorted double linked list corrupted
Thread 1 "sclang" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
49      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
#1  0x00007ffff75f0546 in __GI_abort () at abort.c:79
#2  0x00007ffff7647eb8 in __libc_message (action=action@entry=do_abort, 
    fmt=fmt@entry=0x7ffff7765a78 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007ffff764f91a in malloc_printerr (
    str=str@entry=0x7ffff7768478 "malloc(): unsorted double linked list corrupted")
    at malloc.c:5628
#4  0x00007ffff7652f14 in _int_malloc (av=av@entry=0x7ffff779cba0 <main_arena>, 
    bytes=bytes@entry=262416) at malloc.c:3969
#5  0x00007ffff765368f in _int_memalign (av=av@entry=0x7ffff779cba0 <main_arena>, 
    alignment=alignment@entry=64, bytes=bytes@entry=262304) at malloc.c:4927
#6  0x00007ffff765478c in _mid_memalign (alignment=64, bytes=262304, address=<optimized out>)
    at malloc.c:3514
#7  0x00007ffff7655eb2 in __posix_memalign (size=<optimized out>, alignment=<optimized out>, 
    memptr=0x7fffffffd6d8) at malloc.c:5647
#8  __posix_memalign (memptr=0x7fffffffd6d8, alignment=<optimized out>, size=<optimized out>)
    at malloc.c:5634
#9  0x000055555563ee06 in boost::alignment::aligned_alloc (size=<optimized out>, alignment=64)
    at /home/juliette/Documents/supercollider/external_libraries/boost/boost/align/detail/aligned_alloc_posix.hpp:26
#10 nova::malloc_aligned (bytes=<optimized out>)
    at /home/juliette/Documents/supercollider/common/malloc_aligned.hpp:36
#11 pyr_new_area (size=<optimized out>)
    at /home/juliette/Documents/supercollider/lang/LangSource/InitAlloc.cpp:31
#12 0x000055555567f99d in AllocPool::NewArea (this=0x55555595c2b0, inAreaSize=262144)
    at /home/juliette/Documents/supercollider/common/SC_AllocPool.cpp:191
#13 0x000055555567fe53 in AllocPool::Alloc (this=0x55555595c2b0, inReqSize=<optimized out>)
    at /home/juliette/Documents/supercollider/common/SC_AllocPool.cpp:390
#14 0x00005555556b34e3 in AdvancingAllocPool::AddChunk (this=0x555555cd0450, 
    inSize=<optimized out>)
    at /home/juliette/Documents/supercollider/lang/LangSource/AdvancingAllocPool.cpp:50
#15 0x00005555556b358c in AdvancingAllocPool::Alloc (this=this@entry=0x555555cd0450, 
    reqsize=<optimized out>)
    at /home/juliette/Documents/supercollider/lang/LangSource/AdvancingAllocPool.cpp:66
#16 0x0000555555592189 in PyrGC::Allocate (inRunCollection=<optimized out>, 
    sizeclass=<optimized out>, inNumBytes=128, this=0x555555cd0440)
    at /home/juliette/Documents/supercollider/lang/LangSource/GC.h:329
#17 PyrGC::NewFrame (this=0x555555cd0440, inNumBytes=128, inFlags=inFlags@entry=0,
    inFormat=inFormat@entry=1, inAccount=<optimized out>)
    at /home/juliette/Documents/supercollider/lang/LangSource/GC.cpp:392
#18 0x000055555559aac7 in executeMethod (g=0x5555558025c0 <gVMGlobals>, meth=0x555555bc4040, 
    numArgsPushed=2) at /home/juliette/Documents/supercollider/lang/LangSource/PyrMessage.cpp:1055
#19 0x0000555555592449 in Interpret (g=0x2, g@entry=0x5555558025c0 <gVMGlobals>)
    at /home/juliette/Documents/supercollider/lang/LangSource/PyrInterpreter3.cpp:2909
#20 0x000055555563f758 in runInterpreter (g=0x5555558025c0 <gVMGlobals>, 
    selector=<optimized out>, numArgsPushed=<optimized out>)
    at /home/juliette/Documents/supercollider/lang/LangSource/PyrInterpreter3.cpp:127
#21 0x0000555555643a94 in runLibrary (selector=<optimized out>)
    at /home/juliette/Documents/supercollider/lang/LangSource/PyrLexer.cpp:2269
#22 0x0000555555678610 in SC_LanguageClient::runLibrary (symbol=0x5555559d02d8, 
    this=0x7ffff7f86f90 <__GI___pthread_key_create>)
    at /home/juliette/Documents/supercollider/lang/LangSource/SC_LanguageClient.cpp:160
#23 SC_LanguageClient::executeFile (this=this@entry=0x5555558f92e0, 
    fileName=fileName@entry=0x7fffffffe0a6 "/home/juliette/test.sc")
    at /home/juliette/Documents/supercollider/lang/LangSource/SC_LanguageClient.cpp:180
#24 0x000055555559e39d in SC_TerminalClient::run (this=0x5555558f92e0, argc=<optimized out>, 
    argv=<optimized out>)
    at /home/juliette/Documents/supercollider/lang/LangSource/SC_TerminalClient.cpp:266
#25 0x000055555558d39e in main (argc=2, argv=0x7fffffffdce8)
    at /home/juliette/Documents/supercollider/lang/LangSource/cmdLineFuncs.cpp:27
```
Looks like the garbage collection is busted.

**Comment by JRegimbal** [comment]
Hoping to avoid it by using parseJSONFile directly in 412a791d1f1b7a614d1db0ef129cb536262bd9f9. I haven't replicated since in a couple thousand iterations, so hopefully it's at least occurring less frequently than before.

**Comment by JRegimbal** [comment]
Never mind, as soon as I hit enter and sent it again I got another backtrace.
```
Thread 1 "sclang" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
49      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
#1  0x00007ffff75f0546 in __GI_abort () at abort.c:79
#2  0x00007ffff7647eb8 in __libc_message (action=action@entry=do_abort, 
    fmt=fmt@entry=0x7ffff7765a78 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007ffff764f91a in malloc_printerr (
    str=str@entry=0x7ffff7767e20 "malloc_consolidate(): invalid chunk size") at malloc.c:5628
#4  0x00007ffff76509e0 in malloc_consolidate (av=av@entry=0x7ffff779cba0 <main_arena>)
    at malloc.c:4714
#5  0x00007ffff7652855 in _int_malloc (av=av@entry=0x7ffff779cba0 <main_arena>, 
    bytes=bytes@entry=262416) at malloc.c:3924
#6  0x00007ffff765368f in _int_memalign (av=av@entry=0x7ffff779cba0 <main_arena>, 
    alignment=alignment@entry=64, bytes=bytes@entry=262304) at malloc.c:4927
#7  0x00007ffff765478c in _mid_memalign (alignment=64, bytes=262304, address=<optimized out>)
    at malloc.c:3514
#8  0x00007ffff7655eb2 in __posix_memalign (size=<optimized out>, alignment=<optimized out>, 
    memptr=0x7fffffffd6d8) at malloc.c:5647
#9  __posix_memalign (memptr=0x7fffffffd6d8, alignment=<optimized out>, size=<optimized out>)
    at malloc.c:5634
#10 0x000055555563ee06 in boost::alignment::aligned_alloc (size=<optimized out>, alignment=64)
    at /home/juliette/Documents/supercollider/external_libraries/boost/boost/align/detail/aligned_alloc_posix.hpp:26
#11 nova::malloc_aligned (bytes=<optimized out>)
    at /home/juliette/Documents/supercollider/common/malloc_aligned.hpp:36
#12 pyr_new_area (size=<optimized out>)
    at /home/juliette/Documents/supercollider/lang/LangSource/InitAlloc.cpp:31
#13 0x000055555567f99d in AllocPool::NewArea (this=0x55555595c2b0, inAreaSize=262144)
    at /home/juliette/Documents/supercollider/common/SC_AllocPool.cpp:191
#14 0x000055555567fe53 in AllocPool::Alloc (this=0x55555595c2b0, inReqSize=<optimized out>)
    at /home/juliette/Documents/supercollider/common/SC_AllocPool.cpp:390
#15 0x00005555556b34e3 in AdvancingAllocPool::AddChunk (this=0x555555cd0450, 
    inSize=<optimized out>)
    at /home/juliette/Documents/supercollider/lang/LangSource/AdvancingAllocPool.cpp:50
#16 0x00005555556b358c in AdvancingAllocPool::Alloc (this=this@entry=0x555555cd0450, 
    reqsize=<optimized out>)
    at /home/juliette/Documents/supercollider/lang/LangSource/AdvancingAllocPool.cpp:66
#17 0x0000555555592189 in PyrGC::Allocate (inRunCollection=<optimized out>, 
    sizeclass=<optimized out>, inNumBytes=144, this=0x555555cd0440)
    at /home/juliette/Documents/supercollider/lang/LangSource/GC.h:329
#18 PyrGC::NewFrame (this=0x555555cd0440, inNumBytes=144, inFlags=inFlags@entry=0, 
    inFormat=inFormat@entry=1, inAccount=<optimized out>)
    at /home/juliette/Documents/supercollider/lang/LangSource/GC.cpp:392
#19 0x000055555559aac7 in executeMethod (g=0x5555558025c0 <gVMGlobals>, meth=0x555555e51bc0, 
    numArgsPushed=4) at /home/juliette/Documents/supercollider/lang/LangSource/PyrMessage.cpp:1055
#20 0x0000555555592a77 in Interpret (g=0x2, g@entry=0x5555558025c0 <gVMGlobals>)
    at /home/juliette/Documents/supercollider/lang/LangSource/PyrInterpreter3.cpp:2918
#21 0x000055555563f758 in runInterpreter (g=0x5555558025c0 <gVMGlobals>, 
    selector=<optimized out>, numArgsPushed=<optimized out>)
    at /home/juliette/Documents/supercollider/lang/LangSource/PyrInterpreter3.cpp:127
#22 0x0000555555643a94 in runLibrary (selector=<optimized out>)
    at /home/juliette/Documents/supercollider/lang/LangSource/PyrLexer.cpp:2269
#23 0x0000555555678610 in SC_LanguageClient::runLibrary (symbol=0x5555559d02d8, 
    this=0x7ffff7f86f90 <__GI___pthread_key_create>)
    at /home/juliette/Documents/supercollider/lang/LangSource/SC_LanguageClient.cpp:160
#24 SC_LanguageClient::executeFile (this=this@entry=0x5555558f92e0, 
    fileName=fileName@entry=0x7fffffffe0a6 "/home/juliette/test.sc")
    at /home/juliette/Documents/supercollider/lang/LangSource/SC_LanguageClient.cpp:180
#25 0x000055555559e39d in SC_TerminalClient::run (this=0x5555558f92e0, argc=<optimized out>, 
    argv=<optimized out>)
    at /home/juliette/Documents/supercollider/lang/LangSource/SC_TerminalClient.cpp:266
#26 0x000055555558d39e in main (argc=2, argv=0x7fffffffdce8)
    at /home/juliette/Documents/supercollider/lang/LangSource/cmdLineFuncs.cpp:27
```

**Comment by jeffbl** [comment]
@JRegimbal Any further insight into how often this occurs, or if anything in particular triggers it? From the above, sounds like <1% of requests will be hit with this, and it results in a single rendering being messed up, but then the next is likely fine. Any other bad effects found when we hit this?

**Comment by JRegimbal** [comment]
No other bad effects and I don't totally know the actual percentage in practice. It doesn't seem to just be caused by number of iterations so it may be more frequent under normal use. That being said, it's still small. One suggestion was that it may be a result of the file limit, but there isn't any indication in dmesg of that happening. Otherwise, I don't think we have a solid explanation yet, let alone a possible fix.

**Comment by JRegimbal** [comment]
There isn't a new version of SuperCollider and sadly I think being able to properly debug and fix this is out of my wheelhouse. It doesn't seem to have happened recently so my sense is this can likely be pushed until a new version is released or the severity changes.

**Comment by jeffbl** [comment]
Moved to backlog. Can be moved forward again if we get a more solid repro case, or it becomes more intrusive.
