### ISSUE TITLE
depth-map-generator returning bad JSON to orchestrator (GPU setup error?)

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-server#656]
Test version of browser extension. Target unicorn. Go to the person sitting at a laptop picture on the IMAGE homepage. Get Rendering.

NOTE: Unicorn logs show:

```
depth-map-generator_1            | 2023-04-24T21:37:44.771512029Z ERROR:depth-map-generator:Exception on /preprocessor [POST]
depth-map-generator_1            | 2023-04-24T21:37:44.771663782Z Traceback (most recent call last):
depth-map-generator_1            | 2023-04-24T21:37:44.771676496Z   File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 2528, in wsgi_app
depth-map-generator_1            | 2023-04-24T21:37:44.771708847Z     response = self.full_dispatch_request()          
depth-map-generator_1            | 2023-04-24T21:37:44.771719647Z   File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
depth-map-generator_1            | 2023-04-24T21:37:44.771747820Z     rv = self.handle_user_exception(e)                                                                                                           
depth-map-generator_1            | 2023-04-24T21:37:44.771758860Z   File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
depth-map-generator_1            | 2023-04-24T21:37:44.771782054Z     rv = self.dispatch_request()
depth-map-generator_1            | 2023-04-24T21:37:44.771794417Z   File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
depth-map-generator_1            | 2023-04-24T21:37:44.771819814Z     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
depth-map-generator_1            | 2023-04-24T21:37:44.771830594Z   File "/app/depth-map-generator.py", line 115, in depthgenerator
depth-map-generator_1            | 2023-04-24T21:37:44.771856252Z     checkpoint = torch.load("/app/res101.pth")
depth-map-generator_1            | 2023-04-24T21:37:44.771866922Z   File "/opt/conda/lib/python3.7/site-packages/torch/serialization.py", line 789, in load
depth-map-generator_1            | 2023-04-24T21:37:44.771891258Z     return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
depth-map-generator_1            | 2023-04-24T21:37:44.771919430Z   File "/opt/conda/lib/python3.7/site-packages/torch/serialization.py", line 1131, in _load
depth-map-generator_1            | 2023-04-24T21:37:44.771945900Z     result = unpickler.load()                                                                                                                    
depth-map-generator_1            | 2023-04-24T21:37:44.771956590Z   File "/opt/conda/lib/python3.7/site-packages/torch/serialization.py", line 1101, in persistent_load
depth-map-generator_1            | 2023-04-24T21:37:44.771982619Z     load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
depth-map-generator_1            | 2023-04-24T21:37:44.771993569Z   File "/opt/conda/lib/python3.7/site-packages/torch/serialization.py", line 1083, in load_tensor
depth-map-generator_1            | 2023-04-24T21:37:44.772017784Z     wrap_storage=restore_location(storage, location),
depth-map-generator_1            | 2023-04-24T21:37:44.772028735Z   File "/opt/conda/lib/python3.7/site-packages/torch/serialization.py", line 215, in default_restore_location
depth-map-generator_1            | 2023-04-24T21:37:44.772054523Z     result = fn(storage, location)
depth-map-generator_1            | 2023-04-24T21:37:44.772064902Z   File "/opt/conda/lib/python3.7/site-packages/torch/serialization.py", line 182, in _cuda_deserialize
depth-map-generator_1            | 2023-04-24T21:37:44.772077266Z     device = validate_cuda_device(location)
depth-map-generator_1            | 2023-04-24T21:37:44.772080672Z   File "/opt/conda/lib/python3.7/site-packages/torch/serialization.py", line 166, in validate_cuda_device
depth-map-generator_1            | 2023-04-24T21:37:44.772084068Z     raise RuntimeError('Attempting to deserialize object on a CUDA '                                                                             depth-map-generator_1            | 2023-04-24T21:37:44.772088477Z RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine,
 please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.                                                                                                                      
semantic-segmentation_1          | 2023-04-24T21:37:44.871710892Z load checkpoint from local path: /app/upernet_beit-base_8x2_640x640_160k_ade20k-eead221d.pth
semantic-segmentation_1          | 2023-04-24T21:37:45.404583113Z INFO:root:Model loaded
orchestrator_1                   | 2023-04-24T21:37:45.597431212Z Error occured on fetch from http://semantic-segmentation:5000/preprocessor
orchestrator_1                   | 2023-04-24T21:37:45.597459024Z Error while running segmentation
orchestrator_1                   | 2023-04-24T21:37:45.597616358Z Error occured on fetch from http://depth-map-generator:5000/preprocessor
orchestrator_1                   | 2023-04-24T21:37:45.597717998Z FetchError: invalid json response body at http://depth-map-generator:5000/preprocessor reason: Unexpected token '<', "<!doctype "... is not valid
 JSON
orchestrator_1                   | 2023-04-24T21:37:45.597733106Z     at /usr/src/app/node_modules/node-fetch/lib/index.js:273:32
orchestrator_1                   | 2023-04-24T21:37:45.597736393Z     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
orchestrator_1                   | 2023-04-24T21:37:45.597739218Z   type: 'invalid-json'
orchestrator_1                   | 2023-04-24T21:37:45.597741953Z }
```

Expect: No error
Expect: If error occurs, no bad JSON returned, and proper error code is passed to orchestrator.

**Comment by emmanuelwilson** [comment]
I do not see this error on a number of graphics including the one from the IMAGE website which generated this issue.

**Comment by jeffbl** [comment]
@emmanuelwilson I cannot reproduce this morning. I am OK closing with you closing this, and reopening if it comes up again, but before doing so, can you add a comment on what the likely issue was based on the above log information? Is your best guess it was an incompatibility that got ironed out in the nightly `restoreunstable`? Is there something else that would cause such a failure?

If there is a way to capture this error, I'd still recommend doing so and returning an actual return code without the bad JSON, since we should be able to determine where the code went off the rails?

**Comment by emmanuelwilson** [comment]
What confuses me is that I am still checking for JSON output so I am not sure where it could have gone wrong! I looked it over and I honestly don't know how the error could have popped up (also hard to narrow down the issue if it doesn't persist). Your guess is as good as mine but I think you are right that the nightly `restoreunstable` ironed out whatever incompatibility that caused it. I'll definitely be keeping an eye out for it!

**Comment by jeffbl** [comment]
OK, thanks. Suggest that this might be worth a quick discussion with @JRegimbal since it may point out a flaw in how we are vetting preprocessor results before they get to the orchestrator? Might surface an issue in our overall approach that we need to revise.

**Comment by JRegimbal** [comment]
FYI an HTML response will often be thrown by Flask when there's an uncaught error at runtime.
