### ISSUE TITLE
Fix handlers compatibilty with espnet 202304 version

### ISSUE THREAD

**Issue by jaydeepsingh25** [Shared-Reality-Lab/IMAGE-server#681]
With the esnet-tts service updated to latest version of [espnet](https://pypi.org/project/espnet/#history)(202304) , the photo-audio-handler is giving the following error and hence is unbale to generate renderings:
`Received request
Failed to generate audio!
TypeError [ERR_INVALID_THIS]: Value of "this" must be of type URLSearchParams
    at new NodeError (node:internal/errors:399:5)
    at Proxy.has (node:internal/url:500:13)
    at Proxy.<anonymous> (/usr/src/app/node_modules/node-fetch/dist/index.cjs:700:44)
    at new Request (/usr/src/app/node_modules/node-fetch/dist/index.cjs:1036:38)
    at /usr/src/app/node_modules/node-fetch/dist/index.cjs:1220:19
    at new Promise (<anonymous>)
    at fetch (/usr/src/app/node_modules/node-fetch/dist/index.cjs:1218:9)
    at Object.<anonymous> (/usr/src/app/dist/utils.js:141:41)
    at Generator.next (<anonymous>)
Sending response
    at /usr/src/app/dist/utils.js:8:71 {
  code: 'ERR_INVALID_THIS'
}`

I am assuming this should be fixed in all the using tts (photo-audio-haptics, osm-street-handler...). Not sure if I am missing any handler.

**Comment by JRegimbal** [comment]
Won't fix until ESPnet is working in #682.

**Comment by JRegimbal** [comment]
Not an issue with ESPnet - seems to have merely been found at the same time the upgrade was made!
