### ISSUE TITLE
image-multilang-support service cannot start

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-server#866]
On unicorn, image-multilang-support keeps restarting, with the following error. Does not seem to be happening on pegasus, which implies it is an update since our recent deploy?

Assigning to jaydeep since @JRegimbal has moved to architecture role, even though she previously owned services.

```
multilang-support-1               | 2024-08-05T12:39:38.453442370Z [2024-08-05 12:39:38 +0000] [1] [INFO] Starting gunicorn 22.0.0
multilang-support-1               | 2024-08-05T12:39:38.453592141Z [2024-08-05 12:39:38 +0000] [1] [INFO] Listening at: http://0.0.0.0:80 (1)
multilang-support-1               | 2024-08-05T12:39:38.453608261Z [2024-08-05 12:39:38 +0000] [1] [INFO] Using worker: sync
multilang-support-1               | 2024-08-05T12:39:38.455565910Z [2024-08-05 12:39:38 +0000] [7] [INFO] Booting worker with pid: 7
multilang-support-1               | 2024-08-05T12:39:40.809708078Z 24-08-05 12:39 UTC [INFO]: Translator(en, fr) instantiated!
multilang-support-1               | 2024-08-05T12:39:40.818500779Z 24-08-05 12:39 UTC [ERROR]: 'Translator' object has no attribute 'DEVICE_NAME'
multilang-support-1               | 2024-08-05T12:39:40.818515497Z 24-08-05 12:39 UTC [INFO]: Failed to instantiate Translator(en, fr)!
multilang-support-1               | 2024-08-05T12:39:40.818529823Z 24-08-05 12:39 UTC [DEBUG]: Failed to start model: /app/models/opus-mt-en-fr
multilang-support-1               | 2024-08-05T12:39:40.844824014Z 24-08-05 12:39 UTC [INFO]: Translation service is instantiated and ready!
multilang-support-1               | 2024-08-05T12:39:40.845101905Z [2024-08-05 12:39:40 +0000] [7] [ERROR] Exception in worker process
multilang-support-1               | 2024-08-05T12:39:40.845107546Z Traceback (most recent call last):
multilang-support-1               | 2024-08-05T12:39:40.845110982Z   File "/opt/conda/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
multilang-support-1               | 2024-08-05T12:39:40.845134106Z     worker.init_process()
multilang-support-1               | 2024-08-05T12:39:40.845137432Z   File "/opt/conda/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
multilang-support-1               | 2024-08-05T12:39:40.845140878Z     self.load_wsgi()
multilang-support-1               | 2024-08-05T12:39:40.845144044Z   File "/opt/conda/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
multilang-support-1               | 2024-08-05T12:39:40.845147451Z     self.wsgi = self.app.wsgi()
multilang-support-1               | 2024-08-05T12:39:40.845150727Z   File "/opt/conda/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
multilang-support-1               | 2024-08-05T12:39:40.845154043Z     self.callable = self.load()
multilang-support-1               | 2024-08-05T12:39:40.845157339Z   File "/opt/conda/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
multilang-support-1               | 2024-08-05T12:39:40.845160625Z     return self.load_wsgiapp()
multilang-support-1               | 2024-08-05T12:39:40.845163962Z   File "/opt/conda/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
multilang-support-1               | 2024-08-05T12:39:40.845167278Z     return util.import_app(self.app_uri)
multilang-support-1               | 2024-08-05T12:39:40.845170634Z   File "/opt/conda/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
multilang-support-1               | 2024-08-05T12:39:40.845173980Z     mod = importlib.import_module(module)
multilang-support-1               | 2024-08-05T12:39:40.845177297Z   File "/opt/conda/lib/python3.10/importlib/__init__.py", line 126, in import_module
multilang-support-1               | 2024-08-05T12:39:40.845180593Z     return _bootstrap._gcd_import(name[level:], package, level)
multilang-support-1               | 2024-08-05T12:39:40.845183859Z   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
multilang-support-1               | 2024-08-05T12:39:40.845187536Z   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
multilang-support-1               | 2024-08-05T12:39:40.845191052Z   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
multilang-support-1               | 2024-08-05T12:39:40.845194519Z   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
multilang-support-1               | 2024-08-05T12:39:40.845197885Z   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
multilang-support-1               | 2024-08-05T12:39:40.845201342Z   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
multilang-support-1               | 2024-08-05T12:39:40.845204688Z   File "/app/src/translate.py", line 4, in <module>
multilang-support-1               | 2024-08-05T12:39:40.845208194Z     from .utils import LOGGER, Translator, SUPPORTED_LANGS
multilang-support-1               | 2024-08-05T12:39:40.845211401Z   File "/app/src/utils.py", line 191, in <module>
multilang-support-1               | 2024-08-05T12:39:40.845214767Z     .translate([ready_message])[0].pop())
multilang-support-1               | 2024-08-05T12:39:40.845217973Z AttributeError: 'NoneType' object has no attribute 'translate'
multilang-support-1               | 2024-08-05T12:39:40.845222291Z [2024-08-05 12:39:40 +0000] [7] [INFO] Worker exiting (pid: 7)
multilang-support-1               | 2024-08-05T12:39:41.107116607Z [2024-08-05 12:39:41 +0000] [1] [ERROR] Worker (pid:7) exited with code 3
multilang-support-1               | 2024-08-05T12:39:41.107308477Z [2024-08-05 12:39:41 +0000] [1] [ERROR] Shutting down: Master
multilang-support-1               | 2024-08-05T12:39:41.107325108Z [2024-08-05 12:39:41 +0000] [1] [ERROR] Reason: Worker failed to boot.

```

**Comment by JRegimbal** [comment]
Resolved on unicorn, will upgrade on pegasus soon. Closing this issue.
